coverage_service: cobertura_xml
xcodeproj: DarkSkySwift.xcodeproj
workspace: DarkSkySwift.xcworkspace
scheme: DarkSkySwift-iOS
configuration: Debug
source_directory: Sources
output_directory: reports
binary_basename: DarkSkySwift
ignore:
  - scripts/*
  - Tests/*
  - Carthage/*
